package zadania;

import java.sql.*;

public class Cre1 {

  static public void main(String[] args) {
    new Cre1();
  }

Statement stmt; 

Cre1()  {
   Connection con = null;
   try {
      // łączenie z bazą i utworzenie obiektu typu Statement
	   
	   String u = "jdbc:derby://localhost:1527/ksidb;create=true";
	   con = DriverManager.getConnection(u);
	   stmt = con.createStatement();
	   
	   PreparedStatement ps = con.prepareStatement("set schema ?");
	   ps.setString(1,"APP");
	   ps.executeUpdate();
	   
   } catch (Exception exc)  {
     System.out.println(exc);
     System.exit(1);
   }

   // metoda dropTable jest naszą własną metodą napisaną dla skrócenia programu
   // usuwa ona tabelę podaną jako argument
   // Aby w każdych okolicznościach stworzyć nową tabelę AUTOR
   // musimy usunąć ew.  już istniejącą tabelę AUTOR
   dropTable("WYDAWCA");
   dropTable("POZYCJE"); // usunięcie tabeli pochodnej, będącej w relacji z tabelą AUTOR
   dropTable("AUTOR");   // usunięcie tabeli AUTOR

   String crestmt = "create table AUTOR ( AUTID integer not null generated by default as identity,NAME varchar(255) not null,PRIMARY KEY(AUTID))";
   String crestmt1 = "create table WYDAWCA (" + 
   		"        WYDID integer not null generated by default as identity," + 
   		"        NAME varchar(255) not null," + 
   		"        PRIMARY KEY(WYDID)" + 
   		"        )";
   String crestmt2 = "create table POZYCJE (" + 
   		"        ISBN char(13) not null," + 
   		"        AUTID integer not null," + 
   		"        TYTUL varchar(255) not null," + 
   		"        WYDID integer not null," + 
   		"        ROK integer not null," + 
   		"        CENA real," + 
   		"        PRIMARY KEY(ISBN)," + 
   		"        FOREIGN KEY(AUTID) REFERENCES AUTOR(AUTID)," + 
   		"        FOREIGN KEY(WYDID) REFERENCES WYDAWCA(WYDID)" + 
   		"        )";

   try  {
          stmt.executeUpdate(crestmt);            // wykonanie polecenia zapisanego w crestmt
          stmt.executeUpdate(crestmt1);
          stmt.executeUpdate(crestmt2);
          System.out.println("Utworzono tabelę");

   } catch (SQLException exc)  {                      // przechwycenie wyjątku:
      System.out.println("SQL except.: " + exc.getMessage());
      System.out.println("SQL state  : " + exc.getSQLState());
      System.out.println("Vendor errc: " + exc.getErrorCode());
      System.exit(1);
   } finally {
      try {
        stmt.close();
        con.close();
      } catch(SQLException exc) {
        System.out.println(exc);
        System.exit(1);
      }
   }
}

private void dropTable(String tname)  {
   // ....
	try {
		stmt.executeUpdate("drop table " + tname);
	} catch (SQLException ex) {
		System.out.println(ex);
	}

}

}
